import Head from 'next/head'

import Post from '../components/Post'
import PostForm from '../components/PostForm/PostForm'

import styles from '../styles/Home.module.scss'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
            My Posts App!
        </h1>

        <ul className={styles.posts}>
          <li>
            <Post 
            content="algo" 
            date="12/12/12"/>
            
          </li>
          <li>
            <Post   
            content="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ev" 
            date="9/12/2018"
            />
          </li>
          <li>
            <Post   
            content="Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ev" 
            date="9/12/2028"
            />
              
          </li>
        </ul>

        <PostForm/>


      </main>
    </div>
  )
}
